<? $this->layout('Shared/layout') ?>

<? $this->ViewData['Title'] = 'Error' ?>

<div class="d-flex flex-column justify-content-center text-center" style="height: 500px;">
   <span class="text-danger display-6 mx-auto fw-normal">ERROR</span>
   <h1 class="text-danger display-1 mx-auto fw-normal"><?= $this->Model->getCode() ?></h1>
   <p class="lead w-75 mx-auto text-dark fw-normal"><?= $this->Model->getMessage() ?></p>
</div>